# Generated by Django 2.0.5 on 2018-08-10 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20180810_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
